### PR TITLE
Create it_it.json

### PR DESCRIPTION
**Pull request by BlackShadow77**
Added italian translation.

### CODE REVIEW

**Comment by SuperMartijn642** [comment]
Looks good, thank you for the translations!
I will merge them whenever I have some time available.

**Comment by BlackShadow77** [comment]
No problem! Take your time and tell me if u need more translations in other mods.

**Comment by SuperMartijn642** [comment]
Finally got around to it. It will be available as Chunk Loaders 1.1.12.
Thanks again!

**Comment by BlackShadow77** [comment]
Great!
Was a pleasure, not worry!

**Pull request merged**
